// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARvUzAGbCke7zVHO3NDLQxNAperg42vSQ',
    appId: '1:880184122949:web:77d3ea6d906baa651acd2c',
    messagingSenderId: '880184122949',
    projectId: 'seedly-88831',
    authDomain: 'seedly-88831.firebaseapp.com',
    storageBucket: 'seedly-88831.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC546FAvED6yCOA_xpsHS6pZIUU-dQJbWY',
    appId: '1:880184122949:android:66b7dcc4ad198ff01acd2c',
    messagingSenderId: '880184122949',
    projectId: 'seedly-88831',
    storageBucket: 'seedly-88831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-mmXls-Ynwmn9vRrvmsvU58iB_poj2Nw',
    appId: '1:880184122949:ios:69b54011d8c0b5c71acd2c',
    messagingSenderId: '880184122949',
    projectId: 'seedly-88831',
    storageBucket: 'seedly-88831.appspot.com',
    iosClientId: '880184122949-lolg08uffjt372ot1o5o7rf40fh89poc.apps.googleusercontent.com',
    iosBundleId: 'com.example.seedly',
  );
}
